### ISSUE TITLE
Findpath will fail if pathing to a point within the unit radius.

### ISSUE THREAD

**Issue by MintPaw** [hxDaedalus/hxDaedalus#49] opened 2015-06-03 21:36 UTC
You will receive a null object error with traceback:
Called from hxDaedalus.ai.PathFinder.findPath (hxDaedalus/ai/PathFinder.hx line 67)
Called from hxDaedalus.ai.Funnel.findPath (hxDaedalus/ai/Funnel.hx line 235)
Called from hxDaedalus.data.math.Geom2D.getRelativePosition2 (hxDaedalus/data/math/Geom2D.hx line 271)

This still sometimes occurs even if I prevent pathfinding while the target is in 1.5x the radius. Although I may have my radius misaligned. I've had to prevent pathfinding if the object are in 2x the radius to completely eliminate the error.

EDIT: Actually it seems to also fail if one of the coords of the path is the same, like pathing from (0, 200) to (100, 200)

**Comment by azrafe7** [comment] 2015-06-04 01:11
Haven't had the time to test this yet. 

If you have a little example at hand showing the issue (although it should be quite easy to reproduce on our end), it would speed things up toward a solution, and would be really appreciated.

(I'm mainly worring about using/not using the PathSampler, openfl vs luxe vs flash, git vs haxelib, and things like that).

**Comment by Justinfront** [comment] 2015-06-05 00:17
yep not had a chance to look at this but a fork of one of the examples showing the issue would be ideal did you check if this is also an issue on the as3 version?

**Comment by azrafe7** [comment] 2015-06-05 16:54
@MintPaw, cannot reproduce it on my end. Are you using the git version of the lib? What platform are you targeting?

If you can hand us a minimal example reproducing the issue, we'll be glad to look into it.

**Comment by azrafe7** [comment] 2015-06-15 06:48
@MintPaw, I'm assuming this is fixed with latest git ver, so I'm closing it. But feel free to reopen it if you're still experiencing the issue.

**Closed by azrafe7** 2015-06-15 06:48 UTC
