### ISSUE TITLE
error on basic demo

### ISSUE THREAD

**Issue by lo-th** [hxDaedalus/hxDaedalus#62] opened 2015-10-06 12:55 UTC
hello great port i make a version more optimized for javascript 
and i find a error on basic demo 

i we move rotation object to x:400 and y:300
that intersect big line and after some loop you see error 
Uncaught TypeError: Cannot read property 'get_originVertex' of null

with some bad triangles
i try to find the solution

**Comment by lo-th** [comment] 2015-10-06 15:49
find :)

in DDLS.Mesh at splitEdge function the end splice is not good

at line 
if(eLeft_Right.isConstrained) {
if(index != -1)    edges.splice(index, 1, eLeft_Center, eCenter_Right);
else     edges.splice(edges.indexOf(eRight_Left), 1, eRight_Center, eCenter_Left);

now all intersection is perfect

**Comment by azrafe7** [comment] 2015-10-06 16:59
Thanks for reporting!

Should be fixed now.

If you don't mind me asking:

 - what type of optimizations are you doing for js (is there a repo I can take a look at)?
 - how did you track back the bug to the original as3 source? (as it really was just a `+1` needed to emulate as3 splice behaviour, which is different in haxe)

Anyway thank you!

**Comment by lo-th** [comment] 2015-10-06 18:02
yes i look as3 source 
i change dictionary , change new array to []
fixe some loop and add FieldOfView
here the preview 

https://github.com/lo-th/root/blob/gh-pages/daedalus/ddls.js
http://lo-th.github.io/root/daedalus/

next step is push in worker and make cool 3d demo

**Closed** 2015-10-06 19:03 UTC

**Comment by Justinfront** [comment] 2015-10-06 19:16
:+1:

**Comment by azrafe7** [comment] 2015-10-06 23:01
Thank for the merge @Justinfront!

@lo-th So you're building upon the haxejs output, right? Do you have any examples for FieldOfView? (I'm porting it right now, but I'd like to have a way to test it)

**Comment by lo-th** [comment] 2015-10-07 05:42
yes i'm developp for web game without haxejs 
I'm specialized in 3d and physics engine.

i have to test fieldofview 
you have to define mesh and fromEntity
and test each loop isInField(targetEntity);

**Comment by lo-th** [comment] 2015-10-07 10:03
find another error in Mesh sometime .dispose(); is call before remove from array 
so item is not find and no remove

**Comment by lo-th** [comment] 2015-10-07 10:06
also i think collect all data of mesh in array for edge and vertex
and draw all in on pass is better than bind

**Comment by azrafe7** [comment] 2015-10-07 11:10
The `.dispose()` thing should not be an error (I think you're referring to cases like this https://github.com/lo-th/root/blob/f0d25bd2c53e597c28744a41a8700d4071e77f5b/daedalus/ddls.js#L2003-L2012, right?), as it only sets to `null` the inner variables and not the instance itself, so the `.indexOf()` after that should still be able to find it and remove it from the array. I'll need to check this to be sure though.

About the issue with `.traverse()` and `.bind()` you are right that performance-wise it would be better to populate an array and draw in one pass. We made it this way just because we thought that the traversal function could be used for other purposes, and to simplify SimpleView, so we abstracted it away. But might be worth reconsidering if the gain in speed is substantial.

Great feedback @lo-th, if you find any other things please report back, you're being very helpful!

**Comment by azrafe7** [comment] 2015-10-07 12:52
I've tested the change you proposed in drawMesh() (i.e. accumulate vertices and edges, and draw in one pass) in [this branch](https://github.com/azrafe7/hxDaedalus/tree/test-traverse). On neko it gave +12/15 FPS speed up. So I think it's worth changing it.

**Comment by lo-th** [comment] 2015-10-08 05:31
cool 

i think you should add this simple function
DDLS.Squared = function(a,b){ return a*a + b*b; };

and change in Geom2D, Astar, Funnel, Mesh
that remove double calculation example:
DistanceSquared = (p2.x - fromX) * (p2.x - fromX) + (p2.y - fromY) * (p2.y - fromY);// bad
distanceSquared = DDLS.Squared(p2.x - fromX, p2.y - fromY);// good

also why use loop for push in array ? is a haxe limitation maybe

**Comment by Justinfront** [comment] 2015-10-08 12:11
azrafe7 I would be cautious about optimizing on c++/neko target without profiling with recent optimizations that Hugh made that are supposed to give 6x increase in speed. These changes wont yet be in the current hxcpp/haxe build so I guess check against nightlies?

**Comment by azrafe7** [comment] 2015-10-08 20:55
@Justinfront: yes, I agree with you about being cautious (just read Hugh's post: impressive!). But in the specific case of the latest PR (traverse), it seemed _somewhat_ obvious that the performance would benefit from it (and glad to see you've merged it).

@lo-th:

 - squared(): in haxe we could probably have a _very tiny_ speed up by using *and inlining* such a function, not sure you will have some improvements in pure js as there's the overhead of calling the function to take into account (did you run any benchmark for it?)
 - in js you can pass a variable number of args to push(), while in haxe push() only takes a single arg (not that it couldn't be achieved with a macro :stuck_out_tongue_winking_eye:). So instead of littering the code with a bunch of consecutive push() lines, we simply went for this _more compact/readable_ solution. Haven't yet profiled with and without the loops.
 - Yes, I know of poly2tri (there's also a haxe port of it - actually more than one), but this Daedalus lib has more than just Delaunay triangulation: fromBitmap, updatable objects, pathFinding, etc. (yeah I know, maybe someone would say that's too much, but still!). Anyway... relooking at poly2tri's repo I've just found out that there's a pull request in there that seems to provide A* path finding over the triangulation, though I haven't tried it yet. Might be worth investigating? (@justinfront: there's also a Portal class in there, maybe you could be interested in that - if it works that is)

**Comment by azrafe7** [comment] 2015-10-08 22:56
Oh and @lo-th, don't feel put off, I'm still very interested in your feedback :grimacing:

**Comment by Justinfront** [comment] 2015-10-08 23:49
Lo-th have you used stuff like this for setting up bench marking?
https://www.youtube.com/watch?v=ZYMyvkrownQ
I assume tests could involve mesh generation and path finding by mouse point simulation, maybe?

hxDaedalus triangles are 'better' shape than poly2try, so does current solution need optimising or is it just a trade?  would be curious to see a polygonalAI branch replacing array with something more optimal and merging abilities.
https://github.com/polygonal/ai/tree/master/src/de/polygonal/ai/pathfinding

azrafe7 you mentioned poly2tri has a few haxe ports did you have a particular link we should favor to look at?

I think there maybe an option for unrolling some loops in some version of haxe ? My vague opinion on macros are they are still evolving and I don't know them but abstracts may offer similar gains and will change less and I do know them quite well.

**Comment by lo-th** [comment] 2015-10-09 04:47
yes i find only one interesting function for triangle orientation use 
DDLS.Geom2D.Orient2d = function (pa, pb, pc) {
    var detleft = (pa.x - pc.x) * (pb.y - pc.y);
    var detright = (pa.y - pc.y) * (pb.x - pc.x);
    var val = detleft - detright;
    if (val > -(DDLS.EPSILON_SQUARED) && val < (DDLS.EPSILON_SQUARED)) {
        return 0;// collinear
    } else if (val > 0) {
        return -1;// ccw
    } else {
        return 1;// cw
    }
}

**Comment by azrafe7** [comment] 2015-10-09 19:00
@Justinfront: this one contains the PR with A* (https://github.com/nerik/poly2trihx), and the one inside Heaps (https://github.com/ncannasse/heaps/tree/master/hxd/poly2tri) should be pretty stable at this point.

**Comment by lo-th** [comment] 2015-10-09 19:28
http://lo-th.github.io/root/daedalus/index.html
i have a error on mesh.updateObjects
try to find why ?

**Comment by azrafe7** [comment] 2015-10-09 20:01
@lo-th, how to reproduce the error in your demo? Any specific position to click to trigger it?

Nice maze!

Oh, and I've noticed that the mouse clicked position doesn't take scrolling into account.

**Comment by lo-th** [comment] 2015-10-09 20:37
yes for mouse is simple 
is not on this demo is this one, sometime it's crash 
http://lo-th.github.io/root/daedalus/index__.html

**Comment by azrafe7** [comment] 2015-10-09 21:03
I've played with that demo a bit, but I'm still not able to reproduce the error (although I seem to recall that I've encountered something similar in the past). Have you find a reliable way to reproduce it?

**Comment by Justinfront** [comment] 2015-10-10 01:20
if you take the traces out does it work better, noticed quite a lot in console.

**Comment by lo-th** [comment] 2015-10-10 20:12
is a clearly deep calculation probleme of javascript cause of infini loop 
maybe from dictionary class and equality or to little triangulation calculation.

i make more exemples to test this error 
i also see than full recreation of mesh is better than delete and redraw.
40% of proc vs 20 %

**Comment by lo-th** [comment] 2015-10-10 20:18
ha yes for mouse error you have to add
function onMouseMove(e) {
    var rect = e.target.getBoundingClientRect();
    pos.x = e.clientX - rect.left;
    pos.y = e.clientY - rect.top;
};

**Comment by azrafe7** [comment] 2015-10-10 21:07
Thanks for the mouse fix (have not the time to amend it in the repos right now, but I'll do it at some point).

If you manage to find the source of the infinite loop bug please let us know.

PS: I'm also curious about the circular maze, is it procedurally generated, or via bitmap?

**Comment by azrafe7** [comment] 2015-10-10 21:08
Also... please open a different issue when you find something, it would be easier for us keep track of them.

Thanks.

**Comment by lo-th** [comment] 2015-10-10 21:10
for circular maze is bitmap :) 
ok
